export const LANDING_ICON_OPTIONS = [
  "Headphones",
  "Bug",
  "Download",
  "Wrench",
  "BookOpen",
  "CreditCard",
  "Lightbulb",
  "FolderKanban",
  "MessageCircle",
  "MessageSquareText",
  "Settings",
  "HelpCircle",
  "FileText",
  "Zap",
  "Shield",
  "Users",
  "Paperclip",
  "Bell",
  "Ticket",
  "ChartNoAxesCombined",
  "CalendarClock",
  "Sparkles",
  "Clock3",
  "Search",
  "CheckCircle",
];

export const LANDING_COLOR_OPTIONS = [
  { label: "Sky", value: "bg-sky-100 text-sky-700" },
  { label: "Emerald", value: "bg-emerald-100 text-emerald-700" },
  { label: "Amber", value: "bg-amber-100 text-amber-700" },
  { label: "Rose", value: "bg-rose-100 text-rose-700" },
  { label: "Indigo", value: "bg-indigo-100 text-indigo-700" },
  { label: "Violet", value: "bg-violet-100 text-violet-700" },
  { label: "Slate", value: "bg-slate-100 text-slate-700" },
  { label: "Teal", value: "bg-teal-100 text-teal-700" },
];
